spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/totvs_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging.config: classpath:logback-spring-local.xml

