
create table conta (
    data_pagamento date,
    data_vencimento date not null,
    situacao smallint not null check (situacao between 0 and 3),
    tipo_conta smallint not null check (tipo_conta between 0 and 13),
    valor float(53) not null check (valor>=0),
    id bigint generated by default as identity,
    usuario_id bigint not null,
    descricao varchar(255) not null,
    primary key (id)
);

create table usuario (
    ativo boolean not null,
    nivel_usuario smallint not null check (nivel_usuario between 0 and 1),
    id bigint generated by default as identity,
    nome varchar(100) not null,
    senha varchar(100) not null,
    email varchar(200) not null,
    primary key (id),
    unique (email)
);
